version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: yarn start nodemon


  